---
title: "方差"
author: "张嘉辰"
output: 
  html_document:
    toc: true 
    toc_depth: 4
    toc_float: true
    number_sections: false
    theme: lumen
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
body{
    margin: 0 auto;
    font-family: "Microsoft YaHei", arial,sans-serif;
    color: #444444;
    line-height: 1;
    padding: 30px;
}
@media screen and (min-width: 768px) {
    body {
        width: 748px;
        margin: 10px auto;
    }
}
h1, h2, h3, h4 {
    color: #111111;
    font-weight: 400;
    margin-top: 1em;
}

h1, h2, h3, h4, h5 {
	font-family: Georgia, Palatino, serif;
}
h1, h2, h3, h4, h5, p , dl{
    margin-bottom: 16px;
    padding: 0;
}
h1 {
    font-size: 48px;
    line-height: 54px;
}
h2 {
    font-size: 36px;
    line-height: 42px;
}
h1, h2 {
    border-bottom: 1px solid #EFEAEA;
    padding-bottom: 10px;
}
h3 {
    font-size: 24px;
    line-height: 30px;
}
h4 {
    font-size: 21px;
    line-height: 26px;
}
h5 {
    font-size: 18px;
    list-style: 23px;
}
a {
    color: #0099ff;
    margin: 0;
    padding: 0;
    vertical-align: baseline;
}
a:hover {
    text-decoration: none;
    color: #ff6600;
}
a:visited {
    /*color: purple;*/
}
ul, ol {
    padding: 0;
    padding-left: 24px;
    margin: 0;
}
li {
    line-height: 24px;
}
p, ul, ol {
    font-size: 16px;
    line-height: 24px;
}

ol ol, ul ol {
    list-style-type: lower-roman;
}

/*pre {
    padding: 0px 24px;
    max-width: 800px;
    white-space: pre-wrap;
}
code {
    font-family: Consolas, Monaco, Andale Mono, monospace;
    line-height: 1.5;
    font-size: 13px;
}*/

code, pre {
    border-radius: 3px;
    background-color:#f7f7f7;
    color: inherit;
}

code {
    font-family: Consolas, Monaco, Andale Mono, monospace;
    margin: 0 2px;
}

pre {
    line-height: 1.7em;
    overflow: auto;
    padding: 6px 10px;
    border-left: 4px solid #6CE26C;
}

pre > code {
    border: 0;
    display: inline;
    max-width: initial;
    padding: 0;
    margin: 0;
    overflow: initial;
    line-height: inherit;
    font-size: .85em;
    white-space: pre;
    background: 0 0;

}

code {
    color: #666555;
}


/** markdown preview plus 对于代码块的处理有些问题, 所以使用统一的颜色 */
/*code .keyword {
  color: #8959a8;
}

code .number {
  color: #f5871f;
}

code .comment {
  color: #998
}*/

aside {
    display: block;
    float: right;
    width: 390px;
}
blockquote {
    border-left:.5em solid #eee;
    padding: 0 0 0 2em;
    margin-left:0;
}
blockquote  cite {
    font-size:14px;
    line-height:20px;
    color:#bfbfbf;
}
blockquote cite:before {
    content: '\2014 \00A0';
}

blockquote p {
    color: #666;
}

pre, code, tt {

  font-size: 16px;

  font-family: Consolas, "Liberation Mono", Courier, monospace;

}

 

code, tt {

  margin: 0 0px;

  padding: 0px 0px;

  white-space: nowrap;

  border: 1px solid #eaeaea;

  background-color: #f8f8f8;

  border-radius: 3px;

}

 

pre>code {

  margin: 0;

  padding: 0;

  white-space: pre;

  color: #338000;

  border: none;

  background: transparent;

 

}

 

pre {

  background-color: #f8f8f8;

  border: 1px solid #ccc;

  font-size: 16px;

  line-height: 19px;

  overflow: auto;

  padding: 6px 10px;

  border-radius: 3px;

}

 

pre code, pre tt {

  background-color: transparent;

  border: none;

}

/* QUOTES

=============================================================================*/

 

blockquote {

  border-left: 4px solid #DDD;

  padding: 0 15px;

  color: #777;

}

 

blockquote>:first-child {

  margin-top: 0px;

}

 

blockquote>:last-child {

  margin-bottom: 0px;

}

 

/* HORIZONTAL RULES

=============================================================================*/

 

hr {

  clear: both;

  margin: 15px 0;

  height: 0px;

  overflow: hidden;

  border: none;

  background: transparent;

  border-bottom: 4px solid #ddd;

  padding: 0;

}

 


hr {
    text-align: left;
    color: #999;
    height: 2px;
    padding: 0;
    margin: 16px 0;
    background-color: #e7e7e7;
    border: 0 none;
}

dl {
    padding: 0;
}

dl dt {
    padding: 10px 0;
    margin-top: 16px;
    font-size: 1em;
    font-style: italic;
    font-weight: bold;
}

dl dd {
    padding: 0 16px;
    margin-bottom: 16px;
}

dd {
    margin-left: 0;
}

/* Code below this line is copyright Twitter Inc. */

button,
input,
select,
textarea {
    font-size: 100%;
    margin: 0;
    vertical-align: baseline;
    *vertical-align: middle;
}
button, input {
    line-height: normal;
    *overflow: visible;
}
button::-moz-focus-inner, input::-moz-focus-inner {
    border: 0;
    padding: 0;
}
button,
input[type="button"],
input[type="reset"],
input[type="submit"] {
    cursor: pointer;
    -webkit-appearance: button;
}
input[type=checkbox], input[type=radio] {
    cursor: pointer;
}
/* override default chrome & firefox settings */
input:not([type="image"]), textarea {
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}

input[type="search"] {
    -webkit-appearance: textfield;
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}
input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
}
label,
input,
select,
textarea {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;
    font-weight: normal;
    line-height: normal;
    margin-bottom: 18px;
}
input[type=checkbox], input[type=radio] {
    cursor: pointer;
    margin-bottom: 0;
}
input[type=text],
input[type=password],
textarea,
select {
    display: inline-block;
    width: 210px;
    padding: 4px;
    font-size: 13px;
    font-weight: normal;
    line-height: 18px;
    height: 18px;
    color: #808080;
    border: 1px solid #ccc;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
}
select, input[type=file] {
    height: 27px;
    line-height: 27px;
}
textarea {
    height: auto;
}
/* grey out placeholders */
:-moz-placeholder {
    color: #bfbfbf;
}
::-webkit-input-placeholder {
    color: #bfbfbf;
}
input[type=text],
input[type=password],
select,
textarea {
    -webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
    -moz-transition: border linear 0.2s, box-shadow linear 0.2s;
    transition: border linear 0.2s, box-shadow linear 0.2s;
    -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);
    -moz-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1);
}
input[type=text]:focus, input[type=password]:focus, textarea:focus {
    outline: none;
    border-color: rgba(82, 168, 236, 0.8);
    -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
    -moz-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
    box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba(82, 168, 236, 0.6);
}
/* buttons */
button {
    display: inline-block;
    padding: 4px 14px;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;
    line-height: 18px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
    -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
    background-color: #0064cd;
    background-repeat: repeat-x;
    background-image: -khtml-gradient(linear, left top, left bottom, from(#049cdb), to(#0064cd));
    background-image: -moz-linear-gradient(top, #049cdb, #0064cd);
    background-image: -ms-linear-gradient(top, #049cdb, #0064cd);
    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #049cdb), color-stop(100%, #0064cd));
    background-image: -webkit-linear-gradient(top, #049cdb, #0064cd);
    background-image: -o-linear-gradient(top, #049cdb, #0064cd);
    background-image: linear-gradient(top, #049cdb, #0064cd);
    color: #fff;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
    border: 1px solid #004b9a;
    border-bottom-color: #003f81;
    -webkit-transition: 0.1s linear all;
    -moz-transition: 0.1s linear all;
    transition: 0.1s linear all;
    border-color: #0064cd #0064cd #003f81;
    border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
}
button:hover {
    color: #fff;
    background-position: 0 -15px;
    text-decoration: none;
}
button:active {
    -webkit-box-shadow: inset 0 3px 7px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
    -moz-box-shadow: inset 0 3px 7px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
    box-shadow: inset 0 3px 7px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
}
button::-moz-focus-inner {
    padding: 0;
    border: 0;
}
table {
    *border-collapse: collapse; /* IE7 and lower */
    border-spacing: 0;
    width: 100%;
}
table {
    border: solid #ccc 1px;
    -moz-border-radius: 6px;
    -webkit-border-radius: 6px;
    border-radius: 6px;
    /*-webkit-box-shadow: 0 1px 1px #ccc;
    -moz-box-shadow: 0 1px 1px #ccc;
    box-shadow: 0 1px 1px #ccc;   */
}
table tr:hover {
    background: #fbf8e9;
    -o-transition: all 0.1s ease-in-out;
    -webkit-transition: all 0.1s ease-in-out;
    -moz-transition: all 0.1s ease-in-out;
    -ms-transition: all 0.1s ease-in-out;
    transition: all 0.1s ease-in-out;
}
table td, .table th {
    border-left: 1px solid #ccc;
    border-top: 1px solid #ccc;
    padding: 8px;
    text-align: left;
}

table th {
    background-color: #dce9f9;
    background-image: -webkit-gradient(linear, left top, left bottom, from(#ebf3fc), to(#dce9f9));
    background-image: -webkit-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:    -moz-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:     -ms-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:      -o-linear-gradient(top, #ebf3fc, #dce9f9);
    background-image:         linear-gradient(top, #ebf3fc, #dce9f9);
    /*-webkit-box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;
    -moz-box-shadow:0 1px 0 rgba(255,255,255,.8) inset;
    box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;*/
    border-top: none;
    text-shadow: 0 1px 0 rgba(255,255,255,.5);
    padding: 5px;
}

table td:first-child, table th:first-child {
    border-left: none;
}

table th:first-child {
    -moz-border-radius: 4px 0 0 0;
    -webkit-border-radius: 4px 0 0 0;
    border-radius: 4px 0 0 0;
}
table th:last-child {
    -moz-border-radius: 0 4px 0 0;
    -webkit-border-radius: 0 4px 0 0;
    border-radius: 0 4px 0 0;
}
table th:only-child{
    -moz-border-radius: 4px 4px 0 0;
    -webkit-border-radius: 4px 4px 0 0;
    border-radius: 4px 4px 0 0;
}
table tr:last-child td:first-child {
    -moz-border-radius: 0 0 0 4px;
    -webkit-border-radius: 0 0 0 4px;
    border-radius: 0 0 0 4px;
}
table tr:last-child td:last-child {
    -moz-border-radius: 0 0 4px 0;
    -webkit-border-radius: 0 0 4px 0;
    border-radius: 0 0 4px 0;
}

#TOC {
  left: 60px;
  margin: 20px 0px 10px 0px;
}

.main-container {
  max-width: 1800px;
  margin-left: -220px;
  margin-right: -205px;
}

options(width = 600px)

</style>

#方差

```{r warning=FALSE, message=FALSE}
library(readxl)
data <- read_excel("D:/data/案例数据最终版.xlsx", 1)
town_info <- read.csv("D:/data/第二阶段辅助信息.csv")

#1大型 2中型 1小型 1微型
nhiljk <- c(1,2,1,1)
data_df <- as.data.frame(data)
data_df$scale <- factor(data_df$scale, levels = c("大型", "中型", "小型", "微型"), ordered = TRUE)
data_df$location <- factor(data_df$location, levels = c("街道", "乡镇"), ordered = TRUE)

data_town <- split(data_df[,c("town", "scale", "income", "location")], data_df$town)

VYhilj <- c()
scale_label <- c("大型", "中型", "小型", "微型")
#第i个town
for(i in c(1:length(data_town)) )
{
    #大中小微4层
    VYhilj_town <- 0
    for(j in c(1:4)){
      Nhiljk <- nrow(data_town[[i]][data_town[[i]]$scale==scale_label[j], ])
      if(Nhiljk>0){
      Varhiljk <- var(data_town[[i]][data_town[[i]]$scale==scale_label[j], ]$income)
      Varhiljk[is.na(Varhiljk)] <- 0
      nhiljk_temp <- nhiljk[j]
      VYhilj_temp <- sum( (Nhiljk^2) * (1/nhiljk_temp - 1/Nhiljk)*(Varhiljk) )
      VYhilj_town <- VYhilj_town+VYhilj_temp
      }
      
      if(Nhiljk==0){
        VYhilj_town <- VYhilj_town+0
      }
    }
    VYhilj <- c(VYhilj, VYhilj_town)
}


#town名
#ls(data_town)

#3街道 3乡镇
nhil <- c(3,3)

town_info$VYhilj <- VYhilj

data_county <- split(town_info[,c("county", "town", "location", "income", "概率", "VYhilj")], town_info$county)
#head(data_county)


#对每个Nh 共36个 每个算一个向量的Vhi

location_label <- c("街道", "乡镇")
VYhi <- c()
#i是每一个县
for(i in c(1:length(data_county)) )
{
  #街道 乡镇，2层
  VYhi_county <- 0
  for(j in c(1:2)){
    Nhil <- nrow(data_county[[i]][data_county[[i]]$location==location_label[j],])
    if(Nhil>0){
    nhil_temp <- nhil[j]
    #某个县的两个层里的town的概率
    Zhilj <- data_county[[i]][data_county[[i]]$location==location_label[j],]$概率
    VYhilj_county <- data_county[[i]][data_county[[i]]$location==location_label[j],]$VYhilj
    Yhilj <- data_county[[i]][data_county[[i]]$location==location_label[j],]$income
    Yhil <- sum(Yhilj)
    
    VYhi_Nhil1 <- sum(VYhilj_county/Zhilj)
    VYhi_Nhil1_1 <- VYhi_Nhil1/nhil_temp
    VYhi_Nhil2 <- sum(Zhilj*((Yhilj/Zhilj - Yhil)^2))
    VYhi_Nhil2_1 <- VYhi_Nhil2/nhil_temp
    VYhi_temp <- VYhi_Nhil1_1+VYhi_Nhil2_1
    VYhi_county <- VYhi_county+VYhi_temp
    }
    
    if(Nhil==0){
      VYhi_county <- VYhi_county+0
    }
    
  }
  VYhi <- c(VYhi, VYhi_county)
}
#county名
#ls(data_county)

county_info <- read.csv("D:/data/第一阶段辅助信息.csv")
#1区2县
county_info$VYhi <- VYhi
county_info$county_class <- as.character(county_info$county_class)
county_info$county_class[county_info$county_class == "县"] <- "县级别"
county_info$county_class[county_info$county_class == "县级市"] <- "县级别"
county_info$county_class <- factor(county_info$county_class, levels = c("区", "县级别"), ordered = TRUE)

data_city <- split(county_info[,c("county", "county_class", "income", "city", "概率", "VYhi")], county_info$city)
#head(data_city)

countyclass_label <- c("区", "县级别")
nh <- c(1,2)
VY <- c()
#1区2县
#一共18个city
for(i in c(1:length(data_city)))
{
  #区 县级别 2层
  VY_city <- 0
  for(j in 1:2){
    Nh <- nrow(data_city[[i]][data_city[[i]]$county_class==countyclass_label[j],])
    if(Nh>0){
    nh_temp <- nh[j]
    VYhi_city <- data_city[[i]][data_city[[i]]$county_class==countyclass_label[j],]$VYhi
    Zhi <- data_city[[i]][data_city[[i]]$county_class==countyclass_label[j],]$概率
    Yhi <- data_city[[i]][data_city[[i]]$county_class==countyclass_label[j],]$income
    Yh <- sum(Yhi)
    
    VY_Nh1 <- sum(VYhi_city/Zhi)
    VY_Nh1_1 <- VY_Nh1/nh_temp
    VY_Nh2 <- sum(Zhi*((Yhi/Zhi - Yh)^2))
    VY_Nh2_1 <- VY_Nh2/nh_temp
    VY_temp <- VY_Nh1_1+VY_Nh2_1
    #对每个city
    #VY_city <- VY_city+VY_temp
    VY <- c(VY, VY_temp)
    }
    
    if(Nh==0){
      #VY_city <- VY_city+0
      VY_temp <- 0
      VY <- c(VY, VY_temp)
    }
    
  }
  #VY <- c(VY, VY_city)
}


#方差
res_VarY <- sum(VY)
#相对标准误
sqrt(res_VarY)/sum(data$income)

```
